exclude:
  - node_modules
  - scss
  - package.json
  - gruntfile.js
  - start.cmd
  - coffee


url: "http://marcobaumer.de"

markdown: kramdown

name: Marco Baumer
email: mbaumer90@gmail.com
location: Mannheim, Germany
job : Business Solution Consultant

skills:
  - E-Commerce
  - E-Marketing
  - Data Mining
  - Scrum
  - Product Owner
  - Requirements Engineering

vita:
  - company: BASF Business Services GmbH
    period: September 2015 - present
    job: Business Solution Consultant
  - company: BASF Business Services GmbH
    period: October 2013 - August 2015
    job: Project Office
  - company: BASF Business Services GmbH
    period: October 2010 - September 2013
    job: Working Student

education:
  - name: University of Mannheim
    period: September 2013 - October 2015
    location: Mannheim, Germany
    studies: M.Sc. Business Informatics
  - name: University of Alberta
    period: September 2014 - December 2014
    location: Edmonton, Canada
    studies: MBA, Exchange student
  - name: Duale Hochschule Baden-WÃ¼rttemberg
    period: October 2010 - September 2013
    location: Mannheim, Germany
    studies: B.Sc. Business Informatics

honorificSuffix: M.Sc. Business Informatics
